"""Change Episode fields to title and air_date

Revision ID: ebbe99d24bc5
Revises: 67f98040e5af
Create Date: 2025-06-20 03:03:51.596844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbe99d24bc5'
down_revision = '67f98040e5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('air_date', sa.Date(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('air_date')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
